# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userHandle', models.CharField(max_length=128)),
                ('problemLink', models.URLField()),
                ('problemTitle', models.CharField(max_length=128)),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeForces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userHandle', models.CharField(max_length=128)),
                ('problemLink', models.URLField()),
                ('problemTitle', models.CharField(max_length=128)),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemName', models.CharField(max_length=40)),
                ('link', models.URLField()),
                ('tag1', models.CharField(max_length=40)),
                ('tag2', models.CharField(max_length=40)),
                ('tag3', models.CharField(max_length=40)),
                ('tag4', models.CharField(max_length=40)),
                ('tag5', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SPOJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userHandle', models.CharField(max_length=128)),
                ('problemLink', models.URLField()),
                ('problemTitle', models.CharField(max_length=128)),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=128)),
                ('passWord', models.CharField(max_length=128)),
                ('userEmail', models.URLField()),
                ('mobileNo', models.CharField(max_length=128)),
                ('Gender', models.CharField(max_length=1)),
                ('collageOrCompany', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codechefHandle', models.CharField(max_length=40)),
                ('spojHandle', models.CharField(max_length=40)),
                ('codeforcesHandle', models.CharField(max_length=40)),
                ('codechefRating', models.CharField(max_length=40)),
                ('spojRating', models.CharField(max_length=40)),
                ('codeforcesRating', models.CharField(max_length=40))
            ],
        ),
        migrations.AddField(
            model_name='spoj',
            name='userdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.UserData'),
        ),
        migrations.AddField(
            model_name='codeforces',
            name='userdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.UserData'),
        ),
        migrations.AddField(
            model_name='codechef',
            name='userdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.UserData'),
        ),
    ]
