# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhandle',
            name='codechefRating',
        ),
        migrations.RemoveField(
            model_name='userhandle',
            name='codeforcesRating',
        ),
        migrations.RemoveField(
            model_name='userhandle',
            name='spojRating',
        ),
    ]
