# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_auto_20170926_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codechef',
            name='userdata',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='UserHandle',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='collageOrCompany',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='mobileNo',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='passWord',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='year',
        ),
        migrations.AddField(
            model_name='userdata',
            name='codeforcesHandle',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='codeforcesRating',
            field=models.IntegerField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='spojHandle',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.DeleteModel(
            name='CodeChef',
        ),
    ]
