# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_auto_20171120_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='codeforcesRating',
            field=models.IntegerField(null=True),
        ),
    ]
