# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0004_auto_20171120_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemTitle', models.CharField(max_length=128)),
                ('tag', models.CharField(max_length=128)),
            ],
        ),
    ]
