# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0005_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforces',
            name='problemLink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='codeforces',
            name='problemTitle',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='codeforces',
            name='success',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='codeforces',
            name='userHandle',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='problemTitle',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='problems',
            name='tag',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='spoj',
            name='problemLink',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='spoj',
            name='problemTitle',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='spoj',
            name='success',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='spoj',
            name='userHandle',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
