# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0007_auto_20171128_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='codeforcesRating',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='spojRating',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
